//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boiler.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubQuestion
    {
        public int SubQuestionId { get; set; }
        public int QuestionId { get; set; }
        public int QuestionTypeId { get; set; }
        public int CategoryId { get; set; }
        public string Question { get; set; }
        public int OptionsCount { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTimeStamp { get; set; }
        public System.DateTime UpdateTimeStamp { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Question Question1 { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
